#!/usr/bin/env ansible-playbook
---
- name: Shutdown Cluster Nodes
  hosts: cluster_nodes
  become: true

  tasks:
    - name: Trigger immediate system shutdown
      ansible.builtin.shell: "sleep 1 && shutdown -h now"
      async: 1
      poll: 0

    - name: Wait briefly for local SSH connection to close
      ansible.builtin.pause:
        seconds: 2
