#!/usr/bin/env ansible-playbook
---
- name: Remove Managed Node Ansible User
  hosts: all
  gather_facts: false
  become: true
  vars:
    ansible_user: "{{ bootstrap_user }}"
    ansible_ssh_private_key_file: ""

  tasks:
    - name: Remove passwordless sudoers file for management user
      ansible.builtin.file:
        path: "/etc/sudoers.d/{{ ansible_management_user }}"
        state: absent

    - name: Remove management user account and home directory
      ansible.builtin.user:
        name: "{{ ansible_management_user }}"
        state: absent
        remove: true
        force: true

    - name: Flush SSH connections
      ansible.builtin.meta: reset_connection

- name: Clean Control Node Key
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Remove dedicated Ansible SSH private and public key from controller
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519_ansible"
        - "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519_ansible.pub"
